### ISSUE TITLE
proposition

### ISSUE THREAD

**Issue by 1C0D** [rekby/obsidian-paste-transform#2]
Hi, you opened an issue on one of my repositories, 'close similar tab'. I was looking at your GitHub profile and came across this script. I'm working on another plugin that I have already proposed in Obsidian releases to update the 'wrap with shortcuts' plugin. We have made some pull requests on that repository with Mara Li, but the author is not very responsive.

The new version allows working with selection or content in the clipboard using markers and wrapping them around. There are two ways to use these wrappers: through keyboard shortcuts or a menu suggester. I see your approach as a perfect complement. Perhaps adding a regex button to open another menu when creating wrappers and then working with regex instead of markers, like I did. This would provide two approaches to creating these wrappers.

If you are interested and have ideas to extend the plugin, don't hesitate to contact me. The goal is to add more possibilities to a single plugin.
https://github.com/1C0D/obsidian-quick-wrappers

**Comment by rekby** [comment]
Hello :)

Thanks for the invitation.
I doesn't know typescript at all and it will be difficult to collaborate.

**Comment by 1C0D** [comment]
ok. Your script is clean. 
Just a thing about other scripts I watched around the same theme "paste", 
in your "workspace.on("editor-paste"..." after checks on clipboard, you can first check if you have a link using a regex, if you have a link  then prevent default() then your new code replaceSelection...
else return (so you don't replace the initial paste)
If you replace paste for everything, you can have bugs in some situations, especially with some other plugins. They are many issues reported... it's really super hard to do something without interfering with other existing things.

**Comment by rekby** [comment]
Thanks, I have added check for event prevented already.
